name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          # This option seems to work, though the behavior is different from the local cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # This option does something, but subsequent builds don't use the cache
          # cache-from: type=registry,ref=user/app:latest
          # cache-to: type=inline
          # This option does not work
          # cache-from: type=registry,ref=user/app:buildcache
          # cache-to: type=registry,ref=user/app:buildcache,mode=max
